name: Publish Website

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-website.yml
      - .docker/website/**
      - website/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REG_URL }}
          username: ${{ secrets.CONTAINER_REG_USERNAME }}
          password: ${{ secrets.CONTAINER_REG_PASSWORD }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Packages
        run: yarn --immutable --network-timeout 100000
        working-directory: docs

      - name: Build Website
        run: yarn build
        working-directory: docs

      - name: Build WebSite Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docs/dockerfile
          push: true
          tags: ${{ secrets.CONTAINER_REG_DOMAIN }}/ccc-fullstack-workshop-${{ github.ref_name }}:${{ github.run_id }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ccc-p-us1-website
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.CONTAINER_REG_DOMAIN }}/ccc-fullstack-workshop-${{ github.ref_name }}:${{ github.run_id }}
